import React, { useContext, useEffect, useState } from 'react';
import { Container, Form, Button, Card, Alert, Spinner } from 'react-bootstrap';
import 'bootstrap/dist/css/bootstrap.min.css';
import { AuthContext } from './AuthContext';

function ArticleGenerator() {
  const { state } = useContext(AuthContext);
  const [inputText, setInputText] = useState('');
  const [paragraph, setParagraph] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const handleInputChange = (event) => {
    setInputText(event.target.value);
  };

  const formatResponse = (response) => {
    // Add newline characters and improve numbering in lists
    return response.answer.replace(/\n/g, '<br/>').replace(/(\d+\.\s)/g, '<li>$1</li>');
  };

  const handleSubmit = async () => {
    try {
      setError('');
      setParagraph('');
      setLoading(true);

      const response = await fetch('/api/v1/ai/articlegenerator', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${state.user.token}`,
        },
        body: JSON.stringify({ text: inputText }),
      });

      const data = await response.json();

      if (response.ok) {
        const formattedParagraph = formatResponse(data);
        setParagraph(formattedParagraph);
      } else {
        setError('Error generating the paragraph. Please try again.');
      }
    } catch (error) {
      setError('Something went wrong. Please try again later.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <>
      <Container className="mt-3">
        <Card className="mx-auto" style={{ maxWidth: '800px', border: '2px dashed #3498db', padding: '20px', marginBottom: '20px' }}>
          <h3 className="text-center mb-4">Write Article with AI</h3>
          <Form.Group controlId="paragraphInput">
            <Form.Label>Enter Topic</Form.Label>
            <Form.Control as="textarea" rows={6} value={inputText} onChange={handleInputChange} />
          </Form.Group>
          <Button variant="primary" className="w-20 mt-2" onClick={handleSubmit} disabled={loading}>
            Write Article
          </Button>
          {error && <Alert variant="danger" className="mt-3">{error}</Alert>}
          {loading && (
            <div className="mx-auto" style={{ maxWidth: '800px', border: '2px dashed #3498db', padding: '40px', marginBottom: '20px' }}>
              <div className="text-center">
                <Spinner animation="border" role="status" size="lg">
                  <span className="sr-only">Loading...</span>
                </Spinner>
              </div>
            </div>
          )}
          {paragraph && (
            <Card className="mt-3">
              <Card.Body>
                <h5>Article Generated by AI</h5>
                <div dangerouslySetInnerHTML={{ __html: paragraph }} />
              </Card.Body>
            </Card>
          )}
        </Card>
      </Container>
    </>
  );
}

export default ArticleGenerator;
